# Generated by Django 3.1.1 on 2020-09-25 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('latitude', models.FloatField(blank=True)),
                ('longtitude', models.FloatField(blank=True)),
                ('completed_count', models.PositiveIntegerField(default=0)),
                ('completed', models.ManyToManyField(blank=True, related_name='complited', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
