# Generated by Django 3.1.1 on 2020-09-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mountainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='latitude',
            field=models.FloatField(null=True),
        ),
    ]
